### ISSUE TITLE
bot 功能改进

### ISSUE THREAD

**Issue by jqs7** [jqs7/Jqs7Bot#16]
- [x] rule功能改进
- [x] 订阅相关回复改进
- [x] 添加bot页面的README

**Comment by wfjsw** [comment]
感觉可以在redis驱动下根据group id设定每个群不同的rules内容嗯

**Comment by jqs7** [comment]
@wfjsw 😉 等过几天放假慢慢填坑

**Comment by wfjsw** [comment]
P.S. 如果是这种用法的话rules最好从刷屏保护里去掉嗯

**Comment by jqs7** [comment]
@wfjsw (ゝ∀･) 会弄好的

**Comment by wfjsw** [comment]
据记忆 bot是可以直接在人员变动上边加钩子的 所以可以做个进群自动rules神马的w

**Comment by jqs7** [comment]
@wfjsw 咦，那我有空看下API

**Comment by jqs7** [comment]
@wfjsw 得打开所有群组消息才能看得到新成员加入的消息啊_(:3ゝ∠)_

**Comment by wfjsw** [comment]
咩？然而这里https://core.telegram.org/bots#privacy-mode 有写的Service Message

**Comment by wfjsw** [comment]
而且会不会是你打开方式不对（ new_chat_participant 参数

**Comment by jqs7** [comment]
@wfjsw 😂  那上面的Service Message貌似说的是与机器人有关的（即机器人被加入或者移除群组

**Comment by wfjsw** [comment]
巨硬翻译第一弹：【服务消息 (“人”添加或从组中删除等)。】
巨硬翻译第二弹：【是可选的。将新成员添加到组，关于他们的信息 (此成员“可能”是 bot 本身)】

**Comment by jqs7** [comment]
@wfjsw 我测试的结果就是像上面那样orz

**Comment by wfjsw** [comment]
咩？好吧我试试

**Comment by wfjsw** [comment]
（好吧你是对的 要关掉Privacy Mode......

**Comment by jqs7** [comment]
@wfjsw 关掉Privacy Mode = 没了好多好玩的log看，好忧伤……

**Comment by wfjsw** [comment]
噗关掉privacy就是收取全部信息

**Comment by jqs7** [comment]
@wfjsw （我觉得这个问题应该是tg服务端推送的bug

**Comment by wfjsw** [comment]
嘛（然而他们并没有人处理这个bug

**Comment by jqs7** [comment]
@wfjsw 就是接收全部信息的话，就得关掉log了啊，不然log会爆炸

**Comment by wfjsw** [comment]
过滤 :new_moon_with_face:

**Comment by wfjsw** [comment]
噗还不如单独一个bot :new_moon_with_face: :full_moon_with_face: :new_moon_with_face: :full_moon_with_face: :new_moon_with_face:

**Comment by jqs7** [comment]
@wfjsw orz用正则过滤下吧

**Comment by wfjsw** [comment]
:+1:

**Comment by wfjsw** [comment]
/^\//
