### ISSUE TITLE
请添加“闲聊NBA”群 感谢

### ISSUE THREAD

**Issue by muhowch** [jqs7/Jqs7Bot#17]
https://telegram.me/joinchat/05107e8e0106caf4ef00fac18b449902

**Comment by jqs7** [comment]
@muhowch 已收录(ゝ∀･)

**Comment by muhowch** [comment]
烦请更新群链接为 https://telegram.me/bbNBA
感谢

**Comment by jqs7** [comment]
@muhowch 已更新
