### ISSUE TITLE
"丰"的笔画顺序是什么？

### ISSUE THREAD

**Issue by liruqi** [jqs7/Jqs7Bot#19]
---|
--|-
－－｜－
－－－｜
都不对，你确定不是在逗我？

问正常点的问题行么

**Comment by jqs7** [comment]
用汉字或者数字回答，谁要你用符号啦(°ー°〃)

**Comment by liruqi** [comment]
我智商不够用 还是麻烦你告诉我答案吧

度娘和谷歌都不知道的问题也太难了

**Comment by jqs7** [comment]
横横横竖
→_→

**Comment by jqs7** [comment]
安全起见，以上答案30分钟后删除

**Comment by liruqi** [comment]
数字怎么回答？
这种问题是防 bot 的，你这把人类都挡外面了。

改成类似：“丰” 的笔划数量是多少？
答案是 /auth 4 行么

你要不找一个tg群测一下群众的平均智商怎么样。

**Comment by jqs7** [comment]
并不是防bot，是防捣乱的歪果仁的

数字是1112，源自笔画输入法

**Comment by jqs7** [comment]
建议会采纳，谢谢支持

**Comment by liruqi** [comment]
OK。我不会拼音之外的中文输入法。

**Comment by jqs7** [comment]
ε=ε=ε=(~￣▽￣)~

**Comment by festum** [comment]
Damn！我也過不了關，筆畫順序是什麼意思? 台灣完全沒有這種知識@@
我找到解答了 http://huazi.qcrx.cn/zi.asp?id=13
