### ISSUE TITLE
港股&美股投资群 - 程序员玩投资

### ISSUE THREAD

**Issue by Akagi201** [jqs7/Jqs7Bot#35]
本人是个小程序员, 在研究港股, 无奈身边没有炒股的交流的朋友, 很多也是搞A股的. 希望能通过这个群来吸引更多的小伙伴加入进来
https://telegram.me/joinchat/BVdJSQHc1g_ct1hckNfMvg

**Comment by jqs7** [comment]
@Akagi201 已收录
