### ISSUE TITLE
MediaWiki站长交流群

### ISSUE THREAD

**Issue by ghost** [jqs7/Jqs7Bot#38]
MediaWiki是用PHP写成的维基软件，咱希望有志同道合的友人一起来交流呐

https://telegram.me/joinchat/BuDkcQJ5ZNUNNlzHDT3grA

**Comment by jqs7** [comment]
@Zhangjintao 已收录

**Comment by gcshi** [comment]
这个链接是损坏的

**Comment by jqs7** [comment]
@gcshi 大概是过期了 :see_no_evil: 
@KenOokamiHoro 有新的链接么

**Comment by ghost** [comment]
https://telegram.me/joinchat/BuDkcQJ5ZNVAS9sgfAGq4A

**Comment by jqs7** [comment]
@KenOokamiHoro @gcshi 已更新

**Comment by gcshi** [comment]
Thanks you

**Comment by ghost** [comment]
现在是炒鸡群啦😂

https://telegram.me/mediawiki_zh
