### ISSUE TITLE
订阅 RSS 时，有的源貌似会一直重复刷

### ISSUE THREAD

**Issue by tru2dagame** [jqs7/Jqs7Bot#39]
![b41d9b81-e2d2-4b61-ad53-b78dd980dc8a](https://cloud.githubusercontent.com/assets/1673006/12030669/4a60cf62-ae3d-11e5-916e-f7d42931e05e.png)

如图，源地址为：http://www.dgtle.com/rss/dgtle.xml

**Comment by jqs7** [comment]
@tru2dagame 尝试了删除重新添加了么

**Comment by tru2dagame** [comment]
@jqs7 嗯，试过了，我有两个群，都删了重加过，也不行。。。但是订阅的其他两个 RSS 是正常的

**Comment by jqs7** [comment]
原因在于这个rss源有时会对前几篇文章的rss丢掉，过后再重新获取的又是前面完整的rss，如此反复
就表现出了重复刷rss的bug，应该是这个rss源存在的问题
（不是我的锅 (＾o＾)ﾉ

**Comment by tru2dagame** [comment]
那如果比较最新的两条，有没有更新，看有更新再刷新的话，是不是可以解决这个妖怪……

**Comment by jqs7** [comment]
这个丢的条数有点多……而且不确定有多少条

**Comment by tru2dagame** [comment]
囧，这也是一个奇葩……
Jqs7 notifications@github.com于2015年12月29日 周二下午10:31写道：
