### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by ghost** [jqs7/Jqs7Bot#42]

**Comment by jqs7** [comment]
@Dynamicer 已收录

**Comment by nmcoo** [comment]
新群：https://telegram.me/joinchat/Cf59kj1mVBrcMoAgylTsdA
群名称：Evernote User Club
讨论主题：印象笔记 Evernote 用户交流群

**Comment by jqs7** [comment]
@congcong0806 这个群已经收录过了啊
