### ISSUE TITLE
请添加：中文维基百科社群频道 zh-wikipedia

### ISSUE THREAD

**Issue by learningis1st** [jqs7/Jqs7Bot#47]
[中文维基百科社群频道](https://telegram.me/wikipedia_zh) (@wikipedia_zh)，通过RSS推送中文维基百科[最新页面](https://zh.wikipedia.org/wiki/Special:%E6%9C%80%E6%96%B0%E9%A1%B5%E9%9D%A2)及[首页栏目供稿](https://zh.wikipedia.org/wiki/Wikipedia:%E8%81%94%E5%90%88%E4%BE%9B%E7%A8%BF)。
注意⚠️：**仅**建议[维基百科人](https://zh.wikipedia.org/wiki/Wikipedia:%E7%B6%AD%E5%9F%BA%E7%99%BE%E7%A7%91%E4%BA%BA)加入，尤其是[巡查员](https://zh.wikipedia.org/wiki/Wikipedia:%E6%96%B0%E9%A0%81%E9%9D%A2%E5%B7%A1%E6%9F%A5)。（新页面推送很烦人，首页栏目供稿每天仅一次）

**Comment by jqs7** [comment]
@learningis1st channel 广播但不收录

**Comment by learningis1st** [comment]
谢谢，看到了

**Comment by learningis1st** [comment]
现 [@wikipedia_zh](https://telegram.me/wikipedia_zh) 已改为交流群，原巡查频道已移至 [@zhwp_patrol](https://telegram.me/zhwp_patrol)

@wikipedia_zh 今后回作为中文维基百科的一个聊天室使用。聊天室只为与维基百科相关的询问提供援助，而非普通问题的问答服务。

请不要进入后发送“有人吗”等少许文字及垃圾信息，或滥用聊天室，以免浪费系统资源或人力。

（今后会通过[teleirc](https://github.com/FruitieX/teleirc)与[IRC](https://zh.wikipedia.org/zh-cn/Wikipedia:IRC%E8%81%8A%E5%A4%A9%E9%A2%91%E9%81%93)同步）

**Comment by jqs7** [comment]
已修改 (=ﾟωﾟ)=

**Comment by learningis1st** [comment]
谢谢
