### ISSUE TITLE
请添加「Perfect - Server Side Swift」群组

### ISSUE THREAD

**Issue by ShaneQi** [jqs7/Jqs7Bot#49]
群名称： Perfect - Server Side Swift
群主题： Perfect (Perfect.org) 是一个 Web 后端框架，利用 Perfect, 开发者可以用 Swift 语言来完成整个项目开发。此群旨在为关注 Perfect 的开发者提供中文交流的平台。
群链接： https://telegram.me/joinchat/BM0TEQg-5187I3QwbUnQzQ

**Comment by jqs7** [comment]
@qizt 已收录

**Comment by ShaneQi** [comment]
@jqs7 Thanks!
