### ISSUE TITLE
“A股想知道”的邀请链接坏了

### ISSUE THREAD

**Issue by ycdm** [jqs7/Jqs7Bot#53]
https://telegram.me/joinchat/A7yJSgdCL0J41-3EDuvbug

**Comment by jqs7** [comment]
已暂时移除

**Comment by jqs7** [comment]
联系群组建立者更新后会重新收录

**Comment by larryisthere** [comment]
https://telegram.me/joinchat/A7yJSj7rPtOwabcscf6ueg 奇怪，应该没变啊。
